### ISSUE TITLE
Using with Rails

### ISSUE THREAD

**Issue by udiudi** [xevix/grape-throttle#1]
Hi,

I've added:

``` ruby
use Grape::Middleware::ThrottleMiddleware, cache: $redis, user_key: -> (env) do
  account = current_account
  account.nil? ? nil : account.id
end
```

to config.ru (is that the correct place?)

And I'm getting this error:

``` ruby
NoMethodError: undefined method `route_setting' for nil:NilClass
```

What am I doing wrong? :disappointed: 

Thanks!

**Comment by xevix** [comment]
Hey there. Are you using Grape >= 0.10.0? The `route_setting` used in this gem requires it.

**Comment by udiudi** [comment]
Woops, that was the problem. Thanks!

**Comment by xevix** [comment]
@udiudi Actually you did spot a bug. Grape should have been a runtime_dependency. Fixed, and pushed 0.0.1. Thanks for reporting!

**Comment by udiudi** [comment]
:+1:

**Comment by nguyenchiencong** [comment]
with grape 0.11.0 the problem is still here

**Comment by xevix** [comment]
@nguyenchiencong Thanks for reporting. Could you reproduce and post a link to the repo?

**Comment by nguyenchiencong** [comment]
Hi, I just use a normal grape integration with rails and then added your gem. I finally moved back to rack_attack as it seems to be more reliable than a dsl.

Best,
